title: Easun Inverter Dashboard
views:
  - title: Easun Inverter
    path: easun_inverter
    badges: []
    cards:
      - type: entities
        title: Battery Sensors
        entities:
          - sensor.easun_battery_voltage
          - sensor.easun_battery_current
          - sensor.easun_battery_power
          - sensor.easun_battery_state_of_charge
          - sensor.easun_battery_temperature

      - type: entities
        title: PV Sensors
        entities:
          - sensor.easun_pv_total_power
          - sensor.easun_pv_charging_power
          - sensor.easun_pv_charging_current
          - sensor.easun_pv1_voltage
          - sensor.easun_pv1_current
          - sensor.easun_pv1_power
          - sensor.easun_pv2_voltage
          - sensor.easun_pv2_current
          - sensor.easun_pv2_power
          - sensor.easun_pv_generated_today
          - sensor.easun_pv_generated_total

      - type: entities
        title: Grid Sensors
        entities:
          - sensor.easun_grid_voltage
          - sensor.easun_grid_power
          - sensor.easun_grid_frequency

      - type: entities
        title: Output Sensors
        entities:
          - sensor.easun_output_voltage
          - sensor.easun_output_current
          - sensor.easun_output_power
          - sensor.easun_output_apparent_power
          - sensor.easun_output_load_percentage
          - sensor.easun_output_frequency